target-version = "py311"
select = [
    "B",
    "C",
    "E",
    "F",
    "I",
    "RET",
    "S",
    "T",
    "TRY",
    "UP",
    "W",
]
ignore = [
    "C901",
    "E501",
    "T2",
    "TRY003",
]
